name: riverpod_test
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  dio: ^4.0.6 # HTTP Client
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2 # State Management

dev_dependencies:
  flutter_lints: ^2.0.1 # Linter Rules
  flutter_test: # For Widget Testing
    sdk: flutter
  integration_test: # For Integration Testing
    sdk: flutter

  mocktail: ^0.3.0 # Mock Library

flutter:
  uses-material-design: true
